spring:
  application:
    name: linx
  profiles:
    active: dev

# Server configuration
server:
  port: 8080

service:
  pathPrefix: /api/linx

# Logging configuration
logging:
  level:
    root: INFO
    com.linx: DEBUG